Ext.define("TimeTracking.view.Container", {
 extend: 'Ext.tab.Panel',
    xtype: 'framed-tabs',
    
    fullscreen: true,
    frame: true,
  
    defaults: 
	{
        bodyPadding: 5,
        autoScroll: true
    },
	
    items: 
	[{
        title: 'Active Tab',
        html: 'WELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDDWELCOME MICHAEL SAFDSFSDFD SDFFDDDDDD DDDDDDDDDD',
		anchor: '-10, -262'
    }, {
        title: 'Inactive Tab',
        html: 'SD',
		anchor: '-10, -262'
    }, {
        title: 'Disabled Tab',
        disabled: true
    }]
	
});